language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install
  - wget https://phar.phpunit.de/phpcov.phar && php phpcov.phar merge /tmp --clover coverage.xml

script:
  - phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)