language: php

sudo: false

env:
  global:
    - CODECOV_TOKEN=

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install

script:
  - phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash) -f report/coverage.xml -t $CODECOV_TOKEN